[package]
name = "lambda"
version = "0.1.0"
edition = "2024"


[profile.release]
opt-level = 3        # Full optimizations
lto = "fat"          # Link Time Optimization: enable full LTO
codegen-units = 1    # Reduce parallel code generation units for better optimization
panic = "abort"      # Abort on panic, removes unwinding code
strip = true         # Strip symbols from binary
debug = false        # Disable debug info

[dependencies]
anyhow = "1.0.102"
lazy_static = "1.5.0"
llvm-sys = { version = "211.0.1", features = ["prefer-dynamic"] }
serde = { version = "1.0.228", features = ["derive"] }

[dependencies.serde_json]
version = "1.0.149"
features = ["default"]

[dependencies.inkwell]
version = "0.8.0"
features = ["llvm21-1"]


[dependencies.clap]
version = "4.5.47"
features = ["default", "derive"]

[dependencies.lang-c]
version = "0.6"